# Generated by Django 6.0.1 on 2026-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantdb',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=15)),
                ('mobileno', models.IntegerField()),
                ('cuisine', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('is_open', models.CharField()),
            ],
        ),
    ]
